### ISSUE TITLE
Command(s) suggestion: /admin

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1003]
You can use
It to do new admin commands such as

- /admin info [Super | Telnet | Senior] » Super Admin
  - Gives you information about being a Super Admin.
  - Gives you information about being a Telnet Admin.
  - Gives you information about being a Senior Admin.

- /admin suspended » _Super Admin_ #921 
  - Shows the suspended admins

- /admin kick » _Telnet_
  - You can kick an admin

- /admin ban [Purge | Username] » _Senior_ (User must be online)
  - You can ban a admins without them bypassing it.

- /admin unban [Username] » _Senior_ (User must be banned with /admin)
  - You can ban a admins without them bypassing it.

- /admin baninfo » _Super Admin_ [aliases: bi. binfo, bani]
  - You can check the admins ban info

- /admin vanish » _Super Admin_
  - Makes the admin invisible and does not clear with /potion clearall
───────────────────────────────────────────────────
<big><b><center>MORE TO COME</center></b></big>

**Comment by mysteriace** [comment]
The admin info command is not needed as /saconfig info [name] is already in the mod.

**Comment by Sabermc7** [comment]
Object. We just don't need this command, it's basically making another version of /saconfig.

**Comment by DUFCLiam** [comment]
@mysteriace, This one gives you information like Telnet will link to "Telnet For dummies" Senior "Senior training vid?" Super Admin "Super admin training video"

**Comment by PacksGamingHD** [comment]
How would the admin suspending feature work?

**Comment by xDestroyer217** [comment]
I really don't think this is needed at all, the last 4 are listed in another command (forgot what it was), and that the suspending feature would be useless, it's just, this overall, seems kinda ehh, dumb.

**Comment by DUFCLiam** [comment]
@PacksGamingHD It would remove them from Admin then act like doom #921

**Comment by xDestroyer217** [comment]
@DUFCLiam sounds pretty dumb because you listed that it only lists the suspended admins.

**Comment by DUFCLiam** [comment]
ADDED MORE

**Comment by Wild1145** [comment]
This does seem to have quite a few potential issues with regards to the contributing guidelines like with the walls of text commands that we do not really want to have implemented.

**Comment by DUFCLiam** [comment]
@Wild1145, The `/admin info [Super | Telnet | Senior]` command will link them to a training thread for them,

**Comment by JeromSar** [comment]
I don't like any of these features, actually.

The banning system would have to be revamped since admins can bypass bans by default. Additionally, I don't like the idea of having a "suspend" feature in TFM. Suspending is just micromanagement and it comes down to simply unsupering the admin. Regarding the informational commands, the contributing guidelines dictate that text-only commands should be avoided at all costs. Lastly, the vanish feature should probably not be in this command, but in /vanish.

That being said, I'm closing this issue. If you have any more questions, feel free to leave a note. :)

Thanks for contributing!
