### ISSUE TITLE
Senior can use console commands in-game if they logged into telnet

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#1591]
Seniors can access Console level commands in-game if they logged into telnet, this should be easier than open telnet, and write in the command, like

<In-Game but not in Telnet>
/doom rogue admin
 You have no permission for this command
Logged in to telnet, In-Game
/doom rogue admin
Working

**Comment by PacksGamingHD** [comment]
Seniors have access to doom

**Comment by AvalancheYT** [comment]
Packs, I guess you didnt understand the purpose of this. He means when he logged in on telnet and in-game, he can have access to console only commands.

**Comment by DUFCLiam** [comment]
I do not think this should be counted as a bug maybe just made a feature? Unless it works like this:
`Bob [SA]: /gcmd Farah_ doom DUFC_Liam`

**Comment by JeromSar** [comment]
@Adamx120 I pushed a new version to the server. Does this bug still occur?

**Comment by Wild1145** [comment]
Could someone please confirm if this is still a valid bug?

**Comment by Wild1145** [comment]
I have just attempted to execute /doom and /rawsay in game while logged into telnet and it has advised me that said commands may only be executed from the console. I will close this issue due to being unable to recreate the issue, however if someone is able to recreate it in the future then please re-open this PR.
