### ISSUE TITLE
Change Maven Library Process

### ISSUE THREAD

**Issue by Fyrsta** [TotalFreedom/TotalFreedomMod#1888]
Continued Discussion from [here](http://totalfreedom.boards.net/thread/46149/compiling-error?page=2).

Basically, it would be a lot easier for everyone involved if Maven does what Maven is supposed to do, as in get all of the dependencies remotely without relying on user-downloaded files.

Based off of the pom.xml file, this is simple to do. For Spigot I'm sure (I haven't done any MC development in ages, I might be wrong here) that you can just remove the directory link and it'll do it automatically - maybe not.

As for the rest of them, [JitPack](https://jitpack.io/) will handle the rest - I've used it in the dated [iTranxCraft plugin](https://github.com/TranxCraft/iTranxCraft/) without any problems.

This'll make development for newcomers easier as well as maintaining libraries easier for everyone else.

**Comment by JeromSar** [comment]
@WickedGamingUK While I like this idea, there are some things to consider:
- JitPack looks nice, but how does it function? Does it rely on published jar files, or Github releases? Does it correctly work at all times? Should we depend on JitPack's CDN (is it reliable)?
- The Spigot repository does not exist anymore because of legal issues. To obtain Spigot-Server, you must use buildtools. Perhaps we should make a plugin that downloads and runs buildtools for us.

**Comment by Fyrsta** [comment]
JitPack can work with GitHub releases/commits. I've never had any issues whilst using it.

I second that idea about a plugin, it probably wouldn't be too difficult to make.

**Comment by Wild1145** [comment]
Something we use at work to handle dependency management is Nexus. Possibly not practical here, but I would strongly advise changing the Maven dependency management system, as right now this system does really defeat the object of Maven in many ways.

**Comment by Wild1145** [comment]
I've done a bit of research, Spigot has their own Nexus Repo with Spigot and other handy utilities in that we can use and Maven will automatically pull those, and I am currently setting up a Nexus Server for CJFreedom, so any other dependencies can be hosted on there if needed.

**Comment by Wild1145** [comment]
Actually, I've also looked more at Jitpack and it appears to be very similar to Nexus, so I will do a bit more investigation into both and see what would work better.

**Comment by Fyrsta** [comment]
I'd vouch for JitPack, it makes life simple.

**Comment by Wild1145** [comment]
@WickedGamingUK I've done a bit of investigation, and it looks like we may need to use a mix of both. JitPack is working great for 99% of things, however the one issue is in the CraftBukkit and Minecraft server dependencies, as they are not open source anywhere and due to the legality of distributing it, its not in a repo anywhere. So I am currently looking at options there, but otherwise a mix of JitPack and the Spigot Repo is working a treat.

**Comment by JeromSar** [comment]
@Wild1145 As discussed above, it might be worthwile to make a Maven plugin which downloads and runs Buildtools for us. What do you think?

**Comment by Wild1145** [comment]
@JeromSar My aim really is to centralise as much of it as we can to allow for things like CI. Currently you could just run build tools locally and it will place the Jar automatically into your local machines Maven Repo for use. It is an option, and potentially something we'd want to look at if we wanted to customize Spigot or the process for Buildtools, but I think it may be a bit overkill for what the aim here is, and thats just to make the Maven build process automated.

**Comment by JeromSar** [comment]
@Wild1145 I already understood the goal. To automate the build process for use in a CI, BuildTools will have to be run. We cannot expect the CI to do this for us, and this process must be done within Maven, possibly though the use of a (custom) plugin.

**Comment by Wild1145** [comment]
@JeromSar As I say, I am attempting to avoid the need to create a custom plugin, or have a CI system have to build other projects first. Thats why something like a private Nexus Server may be the better solution so we dont end up having to maintain an additional project. Spigot looks to have a CraftBukkit Dependency as part of their Repo, if that is the case then it will solve this issue, but Maven is not resolving it at the current time. Its possible its something I am doing wrong, but if not the work around would be to have a copy of the Spigot build in the local Maven repo, something Build tools does automatically, and something we may just manually edit for the CI system of choice when we get to it.

**Comment by Wild1145** [comment]
@JeromSar So I've been doing some tinkering with IcarusMod and have got to the stage where if you're building it locally it works perfectly, you just have to had run build tools for that version of MC at some point or another (Just as you would currently anyway) and all other dependencies are being resolved. In terms of TravisCI, its not playing nice. Im not all that farmiliar with the TravisCI Config YAML and there's not a lot online to really discuss it or show working build plans, so really we will need to have all dependencies either hosted (Probably the best option, because the CI's are doing some stuff where it builds different parts in isolated containers), and build them like that, the plugin would probably work without issue locally, but I foresee some of the CI's like Travis not working properly with them.

**Comment by Wild1145** [comment]
So for the sake of simplicity and to make it easier in the future I have decided to use a mix of Jitpack for most of the TFM specific repos, and then official repos of Essentials and Spigot for the other dependencies. Im just getting the TF-WorldEdit version we want up and running, then away we go!

**Comment by Wild1145** [comment]
Currently I have worked around the TF-WorldEdit issue and raised a new issue to have this corrected, as the builds appear to be somehow incomplete, but further investigation would be needed there to find out why. Currently TravisCI is having some issues resolving some dependencies that dont appear to be even needed, so tomorrow I will look more into that. you can see how far I have got here: https://github.com/Wild1145/TotalFreedomMod/tree/citest however that one will need some cleaning up before it could be merged anyway.
