### ISSUE TITLE
Better Command Error System

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1926]
So, for known errors in commands currently a message like: Command error[0] displays, I reckon we could greatly improve this across the whole TFM. If a universal error system could be setup: e.g. Command error 1 is null pointer error Command error 2 is server error, etc, it could be very useful to devs who want a rough idea of what the problem is before looking at it in detail.

**Comment by JeromSar** [comment]
@Commodore64x You might think this is a good idea, but with a little more experience with Java and TFM's command system, you would know that this idea does not work out well in practice. The core problem is that there are a potentially infinite amount of errors possible. Rather than providing a code, as you suggested, it is much more useful to provide the full stack trace, and the full error class.

That being said, I don't think this suggestion should be implemented in TFM. Thanks for contributing!
