### ISSUE TITLE
Dump patches and revert to the original build?

### ISSUE THREAD

**Issue by robingall2910** [TotalFreedom/TotalFreedomMod#2006]
I think just getting rid of all the patches and actually following the GitHub repository would be a good idea. If any of the patches that are on the server are important, then they can be also added here quickly as possible.

**Comment by Wild1145** [comment]
I have washed my hands now of the server side update process. I will push an updated version of the current Github version with any patches that I have been made aware of and are happy to merge, other than that the patches will be lost due to non-corporation of those pushing half thought out patching to the server without any consideration for the mess its caused..

**Comment by Wild1145** [comment]
@JeromSar has put a plan in place to handle the patches, that is currently being rolled out.
