### ISSUE TITLE
Updates are touching the server that aren't on GitHub

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2063]
I've increasingly noticed that developers are pushing updates to the TotalFreedomMod and they are going live on the server without any GitHub review. 

Most notably, updates to the FUtil, new titles for markbyron, and also /blockpvp and /blockredstone

**Comment by ghost** [comment]
That, and, /gtfo was recently (allegedly one of marco's updates) broken as it doesn't rollback the player or undo their worldedits. It continues to be that way on the server.

**Comment by Wild1145** [comment]
Unfortunately the custom modifications that are pushed to the server are out of our control, and we are unable to offer any form of support for them. They are unofficial patches, that were not designed to be used. As a result you would need to work with whoever put the version on the server, and whoever built the patch to resolve these issues, because I could not debug the problems even if I wanted to where they are bypassing the standard contribution system.

**Comment by ghost** [comment]
GTFO will not rollback w/e for a while unfortunately, due to the nature of AsyncWorldEdit it overrides WorldEdit's API which is what the TFM uses, so until we hook into the Async API you will have to rollback manually.

**Comment by Wild1145** [comment]
Due to the differences between TF and TFM Development, this is of little concern to me now. If TF wishes to add additional code to the plugin, it is theirs to maintain.

**Comment by Wild1145** [comment]
Closed as above.
