### ISSUE TITLE
A command to show ops how to save builds with worldedit

### ISSUE THREAD

**Issue by hitzzaf** [TotalFreedom/TotalFreedomMod#2095]
We need a command to help ops with saving with world edit.

**Comment by TangoMangoMC** [comment]
There is already an auto broadcaster that EnderLolzeh created:
http://totalfreedom.boards.net/thread/54053/console-scheduled-events

**Comment by hitzzaf** [comment]
the auto broadcaster takes way too long, and it doesn't do it when we really need it. it only does it every hour, when lately the server has crashed almost every 20 minutes or so.

**Comment by ncurran02** [comment]
But we wouldn't like a hard-coded `wall-of-text` in the plugin, do we?

**Comment by lemonsked** [comment]
this would be better in DaedalusMod.
https://github.com/Superior-Development/DaedalusMod

**Comment by mayokek** [comment]
@OxLemonxO, @Wild1145 said he won't be continuing developing the DaedalusMod plugin (that's what I heard).

**Comment by Wild1145** [comment]
@mayokek DadealusMod has had no need for an update. I am happy to continue working on it, however I was under the impression people didnt like having the plugin on the server, and I've gotten a serious amount of shit from TF developers over its being on the server, because people took to modifying it. Im happy for wall of text commands to be in DaedalusMod, as its designed to run in conjunction with TFM on TF. That is its purpose. 

Here however, this issue is superseded by #317
