### ISSUE TITLE
Build Properties No Longer Working

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#2119]
I am not sure if this is an issue isolated to just myself, however when setting the build.properties to show my name and the build number locally (Though we may want this to also be updated on the latest release? Not sure), when you run /tfm everything is null instead of the actual field.

**Comment by Telesphoreo** [comment]
thats what always happens. its an error within the pom.xml. theres a little area that says ok lets make sure were in this directory but that part of it is broken, so you have to change each of the fields that the build properties read to include the project path thing

its explained somewhere in my tfm compile video (4/10/17) around the 4m mark

**Comment by ghost** [comment]
@Telesphoreo @Wild1145 actually all you have to do is move the build.properties file into src/main/resources

**Comment by JeromSar** [comment]
@Commodore64x That is not true.

**Comment by ghost** [comment]
@JeromSar That is true... It makes sense if you think about it. Resource filtering is set to src/main/resources yet the build.properties file is not in that directory. In the code it is referenced as a resource therefore placing it in the correct directory fixes the problem.

**Comment by JeromSar** [comment]
@Commodore64x It is a dirty hack and not the way the problem should be solved.

**Comment by ghost** [comment]
@JeromSar How is it dirty? The code points to that location.

**Comment by Wild1145** [comment]
@Commodore64x I presume because technically the build properties should not be treated as a build artefact in any way shape or form, but as a separate entity that should not be packaged with the build its self.

**Comment by ghost** [comment]
@Wild1145 Then why is it mentioned in the code? It has to be packaged within the build otherwise that is the reason the code throws a NullPointerException, because the file does not exist.

**Comment by Wild1145** [comment]
@Commodore64x The ANT build process doesn't handle build artefacts in the same way as Maven does. Thats why it was designed the way it was originally.

**Comment by Wild1145** [comment]
Some work has been started on this here - https://github.com/TotalFreedom/TotalFreedomMod/commit/0b9960b0d9a2b5f81aa93dfff7869e4f8a99c4b0 - Though there is some work that needs doing, only the build number is currently updating whereas the timestamp and similar are not updating properly in real time.

**Comment by Telesphoreo** [comment]
I fixed it in Fuse. I had a git.properties though as I used a different plugin.

**Comment by Wild1145** [comment]
@Telesphoreo Are you able to link to where you've done this before?

**Comment by Telesphoreo** [comment]
Pom -https://github.com/FuseMinecraft/Fuse/blob/master/pom.xml

Main class - it has the same BuildProperties and another GitProperties -
https://github.com/FuseMinecraft/Fuse/blob/master/src/main/java/us/flowdesigns/fuse/Fuse.java

The downside is that you have to regenerate the git properties every time you want the build date. I use the git properties for the build time and date because I couldn't figure out how to use it in the build properties. If you are not using the git properties for the build time and date there is no need to regenerate it

**Comment by Wild1145** [comment]
@Telesphoreo Thanks for the help here, that Maven plugin made life a lot easier :)

**Comment by Telesphoreo** [comment]
@Wild1145 By the way, there are still issues. I figured out a better way to get the buildDate with build.properties. However, by putting the build properties AND the git properties in the same function, if one is null, they both will return null. Not everyone will have git setup, but everyone will have the build properties. You should split them up into two different functions so that the build properties and git properties are separate (or put them in two different try and catch methods)
