### ISSUE TITLE
TotalFreedomMod uses JDK 8 functionality

### ISSUE THREAD

**Issue by JeromSar** [TotalFreedom/TotalFreedomMod#2148]
Namely: `java.util.function.Function` is used. 

Original issue: https://github.com/TotalFreedom/TotalFreedomMod/issues/2147

**Comment by Wild1145** [comment]
So this was on the 1.12-Alpha branch, which does require JDK 8 to compile, simply because that is what I had at the time to work with and it seems to work most places. If we need to revert support back to JDK 7 as well then that can be done, just not sure if we *need* to support JDK 7 or not, though probably a good idea really.

**Comment by Wild1145** [comment]
Closed as we've moved from 1.7 to 1.8.
