### ISSUE TITLE
Invis only for admins

### ISSUE THREAD

**Issue by Heyitsthatonekid** [TotalFreedom/TotalFreedomMod#266]
so lets say there is an op and he wants to grief so he looks around and says, "No admins around" when really there is an invis admin right there so he starts griefing and the admin comes out of invis and gtfoes.
Why have i said this...
Only Super Admins should be allowed invis so that they can go undercover and alot of other admins agree

**Comment by Wild1145** [comment]
I am bumping this mainly for the reason that a duplicate recently came up, but also because of the 1.8 changes and the addition of gamemode 3. I think we should add a command accessible to admins only to set them into gamemode 3. This I think also removes them from the tab. It doesn't currently remove them from /list, however we could implement that within the command as TFM handles the list setup its self. This is something I have personally added to the DarthCraftMod and it has worked very very well for admins, with players being completely unable to tell if the admins are invis near them or not.

**Comment by AvalancheYT** [comment]
Bump, I don't think this is needed as it will limit the freedom.
According to our server rules & conduct policy, Invisible is allowed:
```e. Players can use invisibility although admins may sometimes remove it in mass (inc. /invis smite) for security purposes.``` Can be found under Section 4e

Read more: http://totalfreedom.boards.net/thread/21065/server-rules-conduct-policy-everybody#ixzz3zzlpfH1M

**Comment by Wild1145** [comment]
This issue has been superseded by #579
