### ISSUE TITLE
MySQL Branch

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#411]
Mainly for a project I am hoping to run that will depend on TFM, it would be nice if TFM had a more extensive use of MySQL, even if it was on its own branch. This is mostly so I dont have to edit TFM and have conflict issues and may help others in the future, but I just wanted to find out how feasible this would be as a setup.

**Comment by JeromSar** [comment]
There's support for SQLite in the UUID branch: https://github.com/TotalFreedom/TotalFreedomMod/pull/406

**Comment by Wild1145** [comment]
@JeromSar I was aware of SQLite, but looking for proper MySQL and if thats something you and @StevenLawson have any plans of supporting, or if its something that I will need to add in a separate fork for my own use?

**Comment by JeromSar** [comment]
@Wild1145 I don't think we'll be needing MySQL anywhere. SQLite is more reliable and better suits our needs. :)

**Comment by Wild1145** [comment]
@JeromSar Okay, thats fair enough. I thought I would ask before putting any work in to my own version!

**Comment by WickedGamingUK** [comment]
@JeromSar What makes SQLite more reliable? Just the fact it's stored in a file and not on a server? There is quite a lot of limitations of using SQLite.

**Comment by JeromSar** [comment]
@WickedGamingUK There's virtually no limitations of using SQLite. The process is exactly the same except that data is transferred directly from the application to the file, completely bypassing the network step thus being more speedy. Additionally, there's less endpoints of failure (SQL server might be down, connection issues, connection timeouts, etc). Lastly, we'd have to find an offsite host for our SQL database, which might cost money and drastically reduce performance.

Another import aspect to consider is transfer speed. Because SQLite databases are hosted locally, it's latency is nearly negligible. This allows SQLite operations to be executed on the primary thread. If the database would be hosted offsite, this would introduce such a significant increase of latency that all SQL operations would have to be executed on a separate thread, both decreasing performance and app complexity (remember that events and commands have less than one tick to execute).

All in all, it's not worth the hassle nor does it provide any significant benefit for TFM.

**Comment by WickedGamingUK** [comment]
@JeromSar There are limitations to SQLite, one of them being no multi-user support and "One of the limitations of SQLite is the write operations. This DBMS allows only one single write*operating to take place at any given time, hence allowing a limited throughput."

The second one could be a concern with multiple things trying to write to the database, but yeah, there isn't any limitations to SQLite that affects it's use here.

**Comment by StevenLawson** [comment]
I know I haven't been very involved in this, but I will mention that for a single application like this it is common to have a dedicated thread, or always use the primary thread, for SQLite operations. This will make any concurrent write concerns a non-issue.
