### ISSUE TITLE
Switch Developers list from player names to UUID

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#420]
With the name changing now supported, I have noticed that the only thing that is not UUID based is the developers list, while its not a big deal as I doubt we will change our names often if at all, its still not really ideal...

**Comment by JeromSar** [comment]
@Wild1145 While I understand why you might want to change this. The developers list is very small and the list can be easily edited. Additionally, developers are usually known by name rather than by UUID. This is one of the reasons why I'm considering switching the famous players list back to name-based.

All in all, it's simply not worth the development effort to implement.

Thanks for contributing!

**Comment by Wild1145** [comment]
@JeromSar Thats fair enough, it was a suggestion to save having to re-commit and compile every time a developer changes name, and makes it uniformed across all servers so if we change our name, no matter what it is, it will show as a developer. Its fair enough it would be more effort than its worth, but it was just an idea to save having to re-compile and such.
