### ISSUE TITLE
y3llow jack3t fix

### ISSUE THREAD

**Issue by PacksGamingHD** [TotalFreedom/TotalFreedomMod#540]
in the player listener there should be something like

if (username.contains("Y3ll0w_Jack3t")) // not sure if contain works i haven't tested it
{
tfm.banplayer // you know what goes here but I'm to lazy to write the entire thing
}

not sure if it works but i think this could be easily implemented

**Comment by JeromSar** [comment]
We're not going to hardcode player bans, sorry.

**Comment by PacksGamingHD** [comment]
why?

**Comment by Wild1145** [comment]
@PacksGamingHD Because its pointless. Hard code banning is kinda a bad idea anyway, because what happened if you had to take TFM off the server? It just means you loose hard-coded bans. The only time I use hard coded banning myself is for the absolute worst of the worst, who even after a full reset should not be able to re-join. For TF its pointless. Hard code banning is not necessary or worth while.
