### ISSUE TITLE
DoSing rcon

### ISSUE THREAD

**Issue by xiDerp** [TotalFreedom/TotalFreedomMod#555]
Yeeeeep, ur rcon be gettin DoSd.  siiimple loic http fl00d, nd ur stupid rcon stops reesponding...yeaaa u mad u mad u mad u mad u mad bro!11!

**Comment by derpfacedirk** [comment]
wut?

**Comment by xDestroyer217** [comment]
lol no one gives a shit flying fuck, your a dumbass anyways.

@JeromSar Spam

**Comment by xDestroyer217** [comment]
the server works without rcon anyways c:

**Comment by jjkatz613** [comment]
In some places ddosing is illegal so.. I would be afraid right now

**Comment by Stampy100** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Wild1145** [comment]
You do realize that rcon is used for next to nothing, and that it has no actual impact on the day to day operations of this server. All your doing if you are DoSing the Rcon is giving away your IP and its doing it rather pathetically... Go and find some server thats home hosted off of a 1mbps connection that you have a chance of making some real affect instead of on a serer on one of the biggest game hosts in the world.
