### ISSUE TITLE
WorldEdit crash detection

### ISSUE THREAD

**Issue by supergameplayer** [TotalFreedom/TotalFreedomMod#568]
We need a way for WorldEdit to automatically detect large edits. If an edit is over 10,000 blocks, WorldEdit should deny it.

**Comment by GotNoFriends** [comment]
Orrr we could just allow //limit 1000

**Comment by StevenLawson** [comment]
I think that it would be more practical to have a watchdog timer on World edit that would kill the edit if it took too long. No telling how complex this would be to implement, however. Setting block limits never really seems to be completely effective.

**Comment by Wild1145** [comment]
@StevenLawson I think thats down to the way that some commands ignore that limit or have a separate way to limit, which is bypassed because players are OP Status. Commands like //regen I think ignore the limits in place, or do for the TF worldEdit anyway. Finding a way to enforce the limit on all commands would definitely help the situation.

**Comment by Wild1145** [comment]
This issue has been superseded by https://github.com/TotalFreedom/TF-WorldEdit/issues/9
