### ISSUE TITLE
Remove "x.x.x.x connected/disconnected" messages

### ISSUE THREAD

**Issue by UltimaTheHawke** [TotalFreedom/TotalFreedomMod#569]
Now, this may need to be in BukkitTelnet, but see here:

From Exbice
"Then what should be done instead is have a throttling feature so you'll see "Closing x connections" every 10 seconds or whatever works well. Or even remove the messages completely unless the server and/or client is in a debug mode."

http://totalfreedom.boards.net/thread/22690/telnet-port-leaked-warp-list?page=1&scrollTo=245243

**Comment by Wild1145** [comment]
As there is no "Debug" mode (that I am aware of anyway for Telnet) removing the messages pose a security issue in as much as we have no idea who's attempting to connect, and there is no way to throttle them because there would still be an attempted connection that should be logged.

**Comment by TheCJGCJG** [comment]
The message should only be logged to Console on a successful connection event (so that it can be viewed from the logviewer and other telnet users) - all failed or timed out attempts could be logged to a seperate file which can be investigated should the need arise.

In addition to this there could be a throttle to the connection attempts, allowing three times per IP per minute, and again, failed connection attempts will not be shown to the console.

**Comment by Explosives** [comment]
I think that instead of logging an IP that comes on the port, it should only log when the user successfully logs in to telnet, and into the game. Saves log space and hassling over LOIC spammers.

**Comment by JeromSar** [comment]
This was patched in https://github.com/TotalFreedom/BukkitTelnet/commit/3272f871e849b0a67c434f646c2057f8eb380fd3

But this issue does not apply to this repository.
