### ISSUE TITLE
Remove ban and unban

### ISSUE THREAD

**Issue by xDestroyer217** [TotalFreedom/TotalFreedomMod#611]
- /ban
- /pardon
- /banip
- /unbanip

**Comment by Wild1145** [comment]
Raise on Essentials please.

**Comment by ImALuckyGuy** [comment]
And then they would use the default Minecraft server /ban commands.

**Comment by tylerhyperHD** [comment]
If you remove it in Essentials, it does nothing, but when I reverted cmd blocker to a previous state, it blocked it successfully. Yet when I hear Darth and wild saying there is something important behind it, it is total b.s. on their end. Either fix it by rolling it back or not fix it and end up having major problems on the server. (there is already so many already)

**Comment by Wild1145** [comment]
@tylerhyperHD Maybe you want to run this project, take over all development and see exactly how far you end up getting with that? When myself, WickedGamingUK, Madgeek or Darth say something, its because generally we like to think we have some sort of a clue as to what the hell we are doing. The command blocker is broken, yes. Reverting it would be stupid in its self as you just waste all the time that was taken to enhance and improve on it. Simply finding where the bug is, and fixing it would be a better use of the time.

I also am not suggesting we remove it on Essentials, simply blocking it so it is a registered command, but you cant use it, that way you wont default to the Spigot version.

**Comment by tylerhyperHD** [comment]
I actually did end up trying it that way and it just defaulted to the
vanilla ban system and did not block the vanilla command at all.

**Comment by JeromSar** [comment]
@tylerhyperHD I'll say it again, this issue has nothing to do with CommandBlocker, and everything to do with Spigot. 

---

Merged to issue: https://github.com/TotalFreedom/TotalFreedomMod/issues/611
