### ISSUE TITLE
Remove IP Admin Access

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#686]
Currently you can get admin access by having EITHER your UUID match the config file, or one of your IP's match the config file.

UUID's from my understanding are supposed to be near impossible to spoof, and even if you could spoof them you would still have the IP as an authentication "Step". What I suggest is making it so both UUID AND IP Must match to get admin, not just IP. 

By doing this you remove the problem of family members having admin access without removing any server security.

**Comment by tylerhyperHD** [comment]
Here is the issue, it is generating a random UUID instead of using mojang's supplied UUID a ton, and that's where it gets you. To be honest, the only way to fix this is to make it so that it checks only the UUID, and not the IP of the player. This also reduces the amount of imposters on the server <<--

**Comment by Wild1145** [comment]
Well I just dont like the idea of the IP being the thing to grand you any privileges, its just not working. Using IP for authentication is good, but not as a sole way to gain access, its like just entering the password and the software picking a random username to grant you access with, its just not that good.

**Comment by JeromSar** [comment]
Here's the current way TFM's UUID and authentication system works. I've thought it through a lot, and I believe it's the best of both worlds.

**UUIDs**
* TFM Attempts to fetch the UUID from the player's username using Mojang API server. Note that we don't obtain the UUID from the Bukkit/Spigot API since that UUID is completely unreliable in offline-mode servers. They can be spoofed and tend to change and be inconsistent.
* If the UUID can not be fetched (The username doesn't exist, or there was a connection error), TFM attempts to spoof the UUID from the username. All spoofed UUIDs will have their first 8 hexadecimal characters set to _deadbeef_, so spoofed UUIDs can be easily identified.
* Player data (e.g. previous IPs, last login time) is stored in a per-UUID configuration file.

**Admin Authentication**
* When the server is in **online-mode**: A player is considered an admin when the UUID matches one of the UUIDs stored in the superadmin list. If the player's IP isn't in the appropriate admin's entry, it will be added.
* When the server is in **offline-mode**: A player is considered an admin when a player's IP matches one of the IPs stored in the superadmin list. If the player's IP matches (and is considered admin), but the UUID does not match the IP the entry belongs to, a red message will appear at log in: "Player [player] is an admin, but using a username not associated with their IP". This message is here to prevent admins from imposing as other admins.
* When the player's IP does not match any IP on file, the player is considered an Impostor.

Continue discussion from here. :)

**Comment by Wild1145** [comment]
>When the server is in offline-mode: A player is considered an admin when a player's IP matches one of the IPs stored in the superadmin list. If the player's IP matches (and is considered admin), but the UUID does not match the IP the entry belongs to, a red message will appear at log in: "Player [player] is an admin, but using a username not associated with their IP". This message is here to prevent admins from imposing as other admins.

Thats the part I am saying that should be removed. You should only get any sort of admin privileges when *both* the UUID and IP match, not one or the other. Removing the IP part of setting someone to admin would remove the issues with having family members, but would not reduce the security.

**Comment by JeromSar** [comment]
@Wild1145 Note that in offline-mode, the UUID has nothing to do with your admin status. Solely the IP is decisive.

Likewise, TFM is an offline-mode server, using solely the UUID to identify admin-status would be wrong on so many levels. Remember that UUIDs are tied to player accounts, not identities. Since TFM is more often than not in offline-mode, all players logging in as admins would receive admin status, including impostors!

Regarding your suggestion, check _both_ the UUID and IP. I think that this would be a bad idea. If, for example, the UUID database for an admin is wiped, the UUID might be resolved differently (or spoofed altogether), resulting in a different UUID and this system is thus unreliable. A sole message indicating that the UUID doesn't match on login is sufficient here.

**Comment by Wild1145** [comment]
@JeromSar Im not too sure why UUID has nothing to do with admin status, and I still dont think its the best way to do things. Surly we could make a better system where IP's are only used as a verification step, not just an instant free ticket to admin access?

**Comment by tylerhyperHD** [comment]
The only issue is Ryan, I think UUID's are safer than IP's since they
basically validate the player as if they were being validated in online
mode. Also IP's can be spoofed or cloaked ya know, and it might not be so
safe either.

**Comment by Wild1145** [comment]
@tylerhyperHD You can probably spoof UUID's as well (I am not too sure), all I am saying is that I dont think that just because someone's IP matches a file should mean they get instant admin, there should be further steps in place.

**Comment by Hockeyfan360** [comment]
"all players logging in as admins would receive admin status, including impostors!"
If they didn't have the admin's IP when they joined, it wouldn't give them admin...

**Comment by JeromSar** [comment]
@Hockeyfan360 You're describing TFM's current behaviour.

**Comment by Hockeyfan360** [comment]
@JeromSar But you supposedly cannot spoof UUIDS. So, not all imposters would be supered. Even if they did spoof the UUID, they would have to go through IP verification.

**Comment by JeromSar** [comment]
@Hockeyfan360 Please read the two long posts above. Not going to repeat myself.

**Comment by tylerhyperHD** [comment]
What I think should happen is if the player is an admin, it refuses to spoof UUID's and checks online mode UUID's only, since the admins have to have a premium account to become admin anyways.

**Comment by JeromSar** [comment]
It comes down to the fact that UUIDs are unreliable and can very easily be spoofed. That being said, this issue can be closed.
