### ISSUE TITLE
Imposters of ops

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#820]
Is there any possible way to stop impostering of ops, then we could always know if ops lie or not about being impostered.

**Comment by JeromSar** [comment]
@LegendIsAwesomes What exactly is your suggestion?

**Comment by LegendIsAwesomes** [comment]
Maybe we could implement a way to prevent ops being impostered. @JeromSar

**Comment by JeromSar** [comment]
@LegendIsAwesomes How exactly do you think that would work?

**Comment by LegendIsAwesomes** [comment]
I am still thinking of a idea, But i should be able to think of one, ATM i'm experimenting in my own TFM.

**Comment by LegendIsAwesomes** [comment]
@wild1145 do you know any simple way of doing this?

**Comment by Wild1145** [comment]
Use a stripped down version of the superadmin verification. Match UUID to Username through the Mojang API. UUID's can not be easily spoofed so this would just cause a flag to appear on login. The same really should be happening with Supers, because from my understanding a client cannot spoof the UUID, so we shouldnt even bother really with IP Verification...

**Comment by LegendIsAwesomes** [comment]
@JeromSar what about what @wild1145 said?

**Comment by JeromSar** [comment]
@Wild1145 Incorrect, UUIDs can be easily spoofed. Since the UUID is sent to the server when the client connects.

**Comment by Wild1145** [comment]
I've had a think on this, and I dont think we need it. At the end of the day this is a freedom server in offline mode... If we wanted to resolve this, we'd just change and run onlinemode=true all the time...

**Comment by JeromSar** [comment]
I don't think there's any way to do this. Your idea sounds good, but is inevitably also impossible.
