### ISSUE TITLE
Add telnet clan admin rank

### ISSUE THREAD

**Issue by OutOfYourMind** [TotalFreedom/TotalFreedomMod#857]
I think we should add a telnet clan admin rank, it will separate the super telnet admin rank, and players will know the difference.

**Comment by JeromSar** [comment]
@OutOfYourMind I don't think we should, for the following reasons:
* STA and STCA are essentially equal in-game. The only difference is that STCAs have access to the console. This doesn't affect any in game mechanics.
* STCA was born out of STA. STCA are essentially still telnet admins.
* Adding another rank which so much similarity will cause only confusion, because the abbreviation and colors are much the same.

**Comment by OutOfYourMind** [comment]
Alright.
