### ISSUE TITLE
TFM 5.0 - No UUID Support

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#879]
The main issue we have at hand with TFM 5.0 is no UUID support. We need to fix that.

**Comment by JeromSar** [comment]
@tylerhyperHD The UUID system was purposely removed. I'll explain below.

Firstly, the UUID system was buggy. It contained a "UUID spoofer" for players with usernames which aren't present in Mojang's UUID database. This turned out to be a bad design practice. Sometimes, polling UUIDs would fail, resulting in duplicate UUIDs in the cached UUID table. This resulted in duplicate player and admin entries.

Secondly, the UUID system was slow. When a player first logged in, a UUID polling would have to occur first. This resulted in slow logins. Additionally, the UUID table would get extremely large (50k+ entries), which would result in extremely slow UUID lookup. This was one of the primary reasons for the lag.

Lastly, the UUID system was near useless. The only reason the UUID system was implemented in the first place, is to allow players to change their username, and still have their original playerdata loaded. As it turns out, this system could be easily circumvented by logging in with another username. It's clear that another solution for this problem needs to be found.
