### ISSUE TITLE
Block /opall -s to seniors

### ISSUE THREAD

**Issue by OnlineRepz** [TotalFreedom/TotalFreedomMod#897]
I don't think -s is needed as most of people always be on creative.

**Comment by Wild1145** [comment]
I agree.

**Comment by JeromSar** [comment]
Why would we ever _remove_ functionality from tfm, @Verdon-Online ?

**Comment by Wild1145** [comment]
I'd only remove it because this only has the purpose of trolling... And I know really admins ahould be mature enough not to use it, but they have and will, I see no harm in removing it or just blocking it for non seniors if not.

**Comment by Verdon-Online** [comment]
Admins can go rogue (abuse) just using that command. (Eg Spamming etc)

**Comment by Obi2** [comment]
@Verdon-Online Admins can go be abusive using any number of the other commands they have access to, many of which can do significantly more damage than this. Limiting functionality just to prevent abuse is counterproductive; if an admin can't be trusted they shouldn't be an admin.

**Comment by Wild1145** [comment]
@Obi2 My point at least is that a super admin should have no need to do this... Restricting it to a senior makes more sense just like /deopall should be.

**Comment by OutOfYourMind** [comment]
Why don't we make it so that opall automatically makes the players creative, and not have any alias' such as -s or -c

**Comment by Verdon-Online** [comment]
Good idea @OutOfYourMind, completely agree with you but there some con about it, some people might want pvp but turn their's gamemode to creative, preventing them to pvp.

**Comment by JacobMathBoy** [comment]
That's a good point @Verdon-Online, and I would even make a pull request to try to put `/opall -s` to senior.

**Comment by OxLemonxO** [comment]
just.... if an admin abuses we can suspend them. this is useless.
i haven't seen any cases of admin abuse using this command.
why block it for seniors?

**Comment by Wild1145** [comment]
@OxLemonxO Do you have any idea how hard it is just to suspend an admin? Its a huge pain in the neck. So preventing an issue is by far the best solution.

**Comment by OnlineRepz** [comment]
Bump

**Comment by vladvilcu2006** [comment]
@OutOfYourMind  No, we shouldn't because if someone PvP's, then we do /opall and it set everyone to creative, what would happen?

**Comment by JeromSar** [comment]
I don't see any reason why this should be a senior-only command. I haven't seen any abuse with this command, and I doubt it'd be useful as a command to abuse with anyway. This command _can_ however be useful in some cases where player's must stay in survival.

Looking at the permissions set up for TFM's commands, currently, only high profile and potentially dangerous commands (such as /saconfig add) are senior-only. There exist only a few exceptions. This command isn't nearly high profile enough to be a senior-only command. If the scenario ever arises where players need to be in survival, supers should have the ability to make those players survival.

With that said, this issue is closed. Thanks for contributing!
