### ISSUE TITLE
Remove smiting all invisible players

### ISSUE THREAD

**Issue by zD12** [TotalFreedom/TotalFreedomMod#959]
Hi,
As clarified, Mark says invisible potions are allowed. See http://totalfreedom.boards.net/post/81230/. As a result, we should remove '/invis smite'

**Comment by DUFCLiam** [comment]
I do not think we shoould remove it because admins such as myself will do

`/invis` - To see who is invisible then if that is above 10 we do

`/invis smite` - To smite the invisible players then we do

`/say Security reasons.` - To tell them why (We do not need to provide a reason.)

**Comment by OnlineRepz** [comment]
Don't use /invis smite, just do /purgeall or /potion clearall

**Comment by JeromSar** [comment]
I agree with @OnlineRepz `/invis clear` would be a good replacement.

**Comment by Wild1145** [comment]
I disagree. The entire argument that a lot of other Issues have had is that we should not be limiting and removing functionality from the plugin. I cant say as I use invis smite, but it is used. Instead we should *ADD* an invis clear function *in addition* to the invis smite function.

**Comment by Adamx120** [comment]
@Wild1145 I've created a PR for adding clear option to invis

**Comment by zD12** [comment]
@Wild1145, well the issue is regarding commands themselves. From a logical standpoint, '/invis smite' doesn't make sense-- why would we smite a user for simply being near an abuser and being spammed by a potion. '/invis smite' punishes random users, not necessarily the person with potions and spamming them onto others. Then, the biggest and only reason why I'm posting, being invisible's allowed. We have nothing outlawing being invisible. Imagine this, we forcefully smite a person because they have something that's allowed-- that's straight up abuse, and that's what we're doing with this command. Doing '/invis' then manually smiting each and every user would be abuse; why are we able to do '/invis smite' and have that as perfectly fine? We shouldn't, doesn't make sense.

**Comment by Wild1145** [comment]
@zD12 Invis smite is there for when people are abusing it in masses, and it does and has happened, and was the main reason for the commands implementation. If we are going to look at commands that have no real need to be in TFM there are quite a few that you can apply this logic to. Take /saconfig clean for example, its not always the admins fault that they are inactive and away from the server, so why should we be punishing them by removing their admin privileges? We do so because it is their responsibility to retain a level of activity, just as it is a players responsibility not to break the rules, and if that means getting smitten from time to time with other players than so be it, or simply doing /potion clear or whatever the command is to clear potions, or even just drinking some milk in game.

**Comment by JeromSar** [comment]
This is a tough call, but I have to agree with @zD12 here. TF's policy dictates that invisibility is allowed, therefore there must not be an explicit function to punish invisible players. Additionally, if a player is invisible or not says very little about that player's intentions. As mentioned before, that player could have been made invisible by a splash potion of another player. That being said, I think that the best solution would be to replace the existing functionality.

**Comment by Wild1145** [comment]
This was merged into the 5.1 Mc 1.10 branch with the commit referenced on the 13th November 2016.
